// Regenerates ue-niagara-ops.mjs from the engine's own op table.
//
//   node niagara/generate-ops.mjs <engine root>
//
// Niagara's operator pins are not UPROPERTYs -- they are built in C++ by FNiagaraOpInfo::Init,
// which is one long, entirely regular function in NiagaraEditorCommon.cpp. Parsing it beats
// hand-copying a hundred signatures, and it is the only file that has to be re-read when the
// engine version moves.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { DEF_ACCESSORS } from "./types.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const engine = process.argv[2];
if (!engine) {
  console.error("usage: node niagara/generate-ops.mjs <engine root>   e.g. F:/UE_5.8");
  process.exit(1);
}

const source = join(engine, "Engine/Plugins/FX/Niagara/Source/NiagaraEditor/Private/NiagaraEditorCommon.cpp");
const src = readFileSync(source, "utf8");

const collect = (re) => {
  const out = new Map();
  for (const m of src.matchAll(re)) if (!out.has(m[1])) out.set(m[1], m[2]);
  return out;
};

// `static FName A(TEXT("A"));` — the pin names, declared once and reused across every op.
const names = collect(/\bFName\s+(\w+)\s*\(\s*TEXT\("([^"]*)"\)\s*\)/g);
// `FString CategoryName(TEXT("Numeric"));` — BuildName glues Category + "::" + Name.
const categories = collect(/\bFString\s+(\w+)\s*\(\s*TEXT\("([^"]*)"\)\s*\)/g);
// `FNiagaraTypeDefinition NumericType = FNiagaraTypeDefinition::GetGenericNumericDef();`
const typeVars = collect(/\bFNiagaraTypeDefinition\s+(\w+)\s*=\s*FNiagaraTypeDefinition::(\w+)\(\)/g);

const resolveName = (token) => {
  const literal = token.match(/^TEXT\("([^"]*)"\)$/);
  if (literal) return literal[1];
  if (names.has(token)) return names.get(token);
  return null;
};

const resolveType = (token) => {
  const direct = token.match(/^FNiagaraTypeDefinition::(\w+)\(\)$/);
  const accessor = direct ? direct[1] : typeVars.get(token);
  return accessor ? DEF_ACCESSORS[accessor] ?? null : null;
};

// Each op starts at an AddDefaulted() and runs until the next one.
const starts = [...src.matchAll(/OpInfos\.AddDefaulted\(\)/g)].map((m) => m.index);
const blocks = starts.map((at, i) => src.slice(at, starts[i + 1] ?? src.length));

const ops = {};
const skipped = [];
for (const block of blocks) {
  const built = block.match(/Op->BuildName\(\s*TEXT\("([^"]*)"\)\s*,\s*(\w+)\s*\)/);
  if (!built) { skipped.push("no BuildName"); continue; }
  const category = categories.get(built[2]);
  if (!category) { skipped.push(`unresolved category ${built[2]}`); continue; }
  const opName = `${category}::${built[1]}`;

  const side = (which) =>
    [...block.matchAll(new RegExp(`Op->${which}\\.Add\\(FNiagaraOpInOutInfo\\(\\s*([^,]+?)\\s*,\\s*([^,]+?)\\s*,`, "g"))]
      .map((m) => [resolveName(m[1]), resolveType(m[2])]);

  const ins = side("Inputs");
  const outs = side("Outputs");
  const bad = [...ins, ...outs].filter(([n, t]) => !n || !t);
  if (bad.length) { skipped.push(`${opName}: unresolved pin`); continue; }

  ops[opName] = {
    in: ins.map(([n, t]) => [n, t]),
    out: outs.map(([n, t]) => [n, t]),
    // `bSupportsAddedInputs` is what lets a spec give Add or Mul a third operand.
    variadic: /Op->bSupportsAddedInputs\s*=\s*true/.test(block) || undefined,
  };
}

const body = Object.entries(ops)
  .map(([name, o]) => {
    const pins = (list) => `[${list.map(([n, t]) => `["${n}", "${t}"]`).join(", ")}]`;
    return `  "${name}": { in: ${pins(o.in)}, out: ${pins(o.out)}${o.variadic ? ", variadic: true" : ""} },`;
  })
  .join("\n");

// An op whose pins the parser cannot resolve is left out rather than guessed at, and named
// here so a missing entry reads as a known gap instead of an oversight.
const omitted = skipped.length
  ? `//\n// Not included (${skipped.length}):\n${[...new Set(skipped)].map((s) => `//   ${s}`).join("\n")}\n`
  : "";

writeFileSync(join(here, "ue-niagara-ops.mjs"), `// GENERATED by niagara/generate-ops.mjs -- do not edit.
//
// Source: Engine/Plugins/FX/Niagara/Source/NiagaraEditor/Private/NiagaraEditorCommon.cpp
//         (FNiagaraOpInfo::Init)
// Engine: ${engine}
//
// Pin names, order and types are the engine's own rather than a guess. Regenerate when moving
// engine version -- op signatures do change.
${omitted}export const OPS = {
${body}
};
`);

console.log(`${Object.keys(ops).length} ops -> niagara/ue-niagara-ops.mjs`);
if (skipped.length) {
  console.log(`skipped ${skipped.length}:`);
  for (const s of [...new Set(skipped)].slice(0, 20)) console.log(`  ${s}`);
}
